$set 100
1 Addr
$set 101
1 Found %d address(es).
$set 253
101 No database loaded.
102 No name specified.
103 Name already exists.
104 Address not found.
105 Cannot alocate memory for the address list.
106 An error occured while loading the address list.
107 An error occured while reading the address.
108 An error occured while creating the new\n\
database. No database was created.
109 An error occured while opening the\n\
database. No database was opened.
198 Modify is not implemented yet.
199 Delete is not implemented yet.
201 Do you really want to quit?

